name: Update stats

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 11 * * *" # every 24 hours
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Update README.md
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'Vishal Shah'
            git config user.email 'vishal12kl@gmail.com'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
