name: Update stats

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'Vishal Shah'
            git config user.email 'vishal12kl@gmail.com'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
